
CREATE TABLE QUESTIONS (QUESTIONID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), SURVEYID BIGINT NOT NULL, PROMPT VARCHAR(255) NOT NULL, GRADETHRESHOLDS VARCHAR(3) NOT NULL, CATEGORY VARCHAR(255) NOT NULL, CONSTRAINT PK_QUESTIONS PRIMARY KEY (QUESTIONID))
