
CREATE TABLE USERS 
(
	USERID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	SURVEYID BIGINT NOT NULL,
	FIRSTNAME VARCHAR(64) NOT NULL,
	LASTNAME VARCHAR(64) NOT NULL,
	EMAIL VARCHAR(512) NOT NULL,
	DISCOUNTCODE VARCHAR(128) NOT NULL,
	USERCOMMENT VARCHAR(1024),
	CONSTRAINT PK_USERS PRIMARY KEY (USERID),
	CONSTRAINT FK_TO_SURVEYS_FROM_USERS FOREIGN KEY (SURVEYID) REFERENCES SURVEYS(SURVEYID)
);